- name: Installs tmux
  apt:
    pkg: tmux
    state: present

- name: Adds tmux pairing scripts
  copy:
    src: "../files/{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
  with_items:
    - tmux-attach
    - tmux-start
    - tmux-stop

